- extensions/camera/README.md
- extensions/camera/examples/item.json
- extensions/camera/json-schema/schema.json
STAC json schema for the **camera extension** specificied in STAC/extension/historical_imagery/README.md
Created using the projection extension code as a guide: https://github.com/stac-extensions/projection
nb: the `$id` and `const` links currently do not work
> feat: camera extension

- LICENSE
Sourced from https://creativecommons.org/licenses/by/4.0/legalcode.txt. GitHub should then recognise license via https://choosealicense.com/licenses/cc-by-4.0/#.
> chore: use license plain text

- validate.sh
Makes it possible to run this script on NixOS and other distributions
with a different path to the Bash shell.
> fix: Use portable shebang line

- extensions/camera/schema.json
- extensions/linz/schema.json
- extensions/quality/schema.json
`oneOf` and `anyOf` containing only one element are unnecessary.
> refactor: Simplify schemas

- README.md
Should reference the file where `schemaMap`s are configured.
> docs: Fix new extension instructions

- extensions/camera/schema.json
- extensions/linz/schema.json
- extensions/quality/schema.json
- extensions/template/schema.json
ref: eb3d4943b34e8e7e000bb5a407d72a536c9ea22d (commit being reverted)
discussion: https://github.com/linz/stac/pull/60#discussion_r715257218
upstream issue: https://github.com/stac-extensions/template/issues/10
These appear to be useful for checking that our own examples are correct, and to remain consistent with all of the JSON Schemas in the STAC community extensions.
If they are removed upstream / determined to no longer be needed, then a new PR and discussion can be created.
> revert: reinstate stac_extensions schema definitions

- extensions/aerial-photo/examples/item.json
- extensions/camera/examples/item.json
- extensions/film/examples/item.json
- extensions/scanning/examples/item.json
These fields shouldn't be there as the extensions are not included in the stac_extensions
> fix: remove eo and file extensions from examples

- extensions/linz/README.md
Noticed processing extension was missing from the list of other extensions used.
> docs: add missing extension to linz extension README

- extensions/linz/README.md
Having /assets/* in the metadata path seems redundant (It's already clear from the table title that we are talking about assets). If not redundant, it's at least inconsistent with how we've documented other metadata.
> docs: remove redundant metadata path info

- extensions/aerial-photo/schema.json
- extensions/aerial-photo/tests/aerial_photo_collection.test.js
- extensions/camera/schema.json
- extensions/film/examples/collection.json
- extensions/film/schema.json
- extensions/film/tests/film_collection.test.js
- extensions/historical-imagery/examples/collection.json
- extensions/historical-imagery/schema.json
- extensions/historical-imagery/tests/historical-imagery_collection.test.js
- extensions/scanning/schema.json
Extensions updated to include summary requirements:
- historical imagery
-  aerial-photo
-  camera
-  scanning 
- film extensions
nb: eo:bands cannot be added to the historical imagery schema as it would be an asset summary (please correct me if I'm wrong here).
> feat: add summaries to historical imagery related extensions

- extensions/linz/README.md
- extensions/linz/schema.json
The following linz geospatial types have been identified from the Historical Imagery metadata:
```
black and white infrared image
color infrared image
```
> feat: add IR linz:geospatial_types

- extensions/historical-imagery/schema.json
- extensions/historical-imagery/tests/historical-imagery_item.test.js
Fixing a mistake - the historical imagery extension should not require the 'instruments' Item field.
> fix: historical imagery should not require instruments field

- README.md
- extensions/aerial-photo/README.md
- extensions/camera/README.md
- extensions/film/README.md
- extensions/historical-imagery/README.md
- extensions/linz/README.md
- extensions/quality/README.md
- extensions/scanning/README.md
When a new release is pushed, web pages are created from the gh-pages branch, and relative links break when hosted on stac.linz.govt.nz.
This change means that the links will work when hosted on stac.linz.govt.nz.
Example and schema links have been added to all readme files so they are consistent.
> fix: broken links on readme web pages and link consistency

- extensions/aerial-photo/schema.json
- extensions/aerial-photo/tests/aerial_photo_item.test.js
- extensions/camera/schema.json
- extensions/film/schema.json
- extensions/historical-imagery/schema.json
- extensions/historical-imagery/tests/historical-imagery_collection.test.js
- extensions/historical-imagery/tests/historical-imagery_item.test.js
- extensions/linz/tests/linz_item.test.js
- extensions/scanning/schema.json
[https://linzgovt.atlassian.net/browse/TDE-239](https://linzgovt.atlassian.net/browse/TDE-239)
Align the following STAC extensions with the linz schema changes made in #177 
- aerial-photo
- camera
- film
- historical-imagery
- scanning
by using `conditional` instead of `oneOf`.
This allows us to get more information from validators that don't provide nested errors on a schema match fail.
> Use `conditional` instead of `oneOf` in extensions

- extensions/aerial-photo/schema.json
- extensions/film/schema.json
- extensions/historical-imagery/schema.json
- extensions/linz/schema.json
- extensions/template/schema.json
See <https://ajv.js.org/strict-mode.html>.
These are the last warnings in our schemas - see `npx ospec 2> >(grep --fixed-strings --invert-match --regex='stac-extensions.github.io' --regex=schemas.stacspec.org >&2)` (this command basically removes the warnings for stac-extensions.github.io and schemas.stacspec.org from standard error, showing only the LINZ-related ajv warnings).
> feat: Fix strict ajv warnings

- extensions/historical-imagery/examples/collection.json
`quality:description` added to the historical imagery collection.json example. 
the topo engineering team still has some development work to do on validating the collection.json objects so the decision was made not to require this field in the json schema just yet.
> feat(historical-imagery): add quality:description to collection

- .github/workflows/fields.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
Avoids quietly using whichever version is the latest starting with the specified version number, which could break at any time.
> fix: Use specific action versions

- extensions/camera/tests/camera_collection.test.mjs
- extensions/camera/tests/camera_item.test.mjs
- extensions/film/tests/film_collection.test.mjs
- extensions/film/tests/film_item.test.mjs
- extensions/historical-imagery/tests/historical-imagery_collection.test.mjs
- extensions/historical-imagery/tests/historical-imagery_item.test.mjs
- extensions/linz/tests/linz_collection.test.mjs
- extensions/linz/tests/linz_item.test.mjs
- extensions/quality/tests/quality_collection.test.mjs
- extensions/scanning/tests/scanning_collection.test.mjs
- extensions/scanning/tests/scanning_item.test.mjs
- extensions/template/tests/template_collection.test.mjs
- extensions/template/tests/template_item.test.mjs
- package.json
ospec does not support auto-resolving ES modules (`*.mjs`), so we have to
specify them all manually.
Also point to renamed `validation.mjs` file.
> fix: run ospec tests

- extensions/historical-imagery/tests/historical-imagery_collection.test.mjs
The original code always ended up with no providers at all, which triggered the expected error. But the point of the test was to test with only a single missing required provider in each case.
> test: Provide stronger missing provider tests

- .github/workflows/test.yaml
- package-lock.json
- package.json
1. Update the engine:
```
jq '.engines.node = "^20.13.1"' package.json | sponge package.json
```
2. Update the lock file:
```
npm install
```
3. Update the uses of `linz/action-typescript`:
```
for path in .github/workflows/*.y*ml; do
yq --inplace '(.jobs.*.steps[] | select(.uses == "linz/action-typescript*").with.node-version) = "20.x"' "$path";
done
```
> build: Bump Node.js to latest LTS, 20.13.1 TDE-1090
